services:
  app_analytics_api:
    image: analytics-api:v1
    build:
      context: .
      dockerfile: Dockerfile
    #environment:
    #  - PORT=8000
    #  - DATABASE_URL=postgres+psycopg://postgres:postgres@db_analytics_api:5433/postgres
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/code:rw
    develop:
      watch:
        - path: Dockerfile
          action: rebuild
        - path: requirements.txt
          action: rebuild
        - path: compose.yaml
          action: rebuild

  db_analytics_api:
    image: timescale/timescaledb:latest-pg17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5433"
    expose:
      - "5433"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data

volumes:
  timescaledb_data:
